# docker-compose.yml

version: "3"
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8888
    ports:
      - "8888:8888"

  frontend:
    build: ./frontend
    command: quasar dev
    ports:
      - "8080:8080"
    depends_on:
      - backend
